# Generated by Django 3.2.3 on 2022-05-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Сегежа', max_length=200, verbose_name='город')),
                ('street', models.CharField(max_length=200, verbose_name='улица')),
                ('house', models.CharField(max_length=10, verbose_name='номер дома')),
                ('rest_address', models.CharField(blank=True, default='-', max_length=250, verbose_name='остаток адреса')),
            ],
            options={
                'verbose_name': 'адрес',
                'verbose_name_plural': 'адреса',
            },
        ),
        migrations.CreateModel(
            name='DisabledAdressesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blackout_datetime', models.CharField(default='08.05.2022-18.46', max_length=20, verbose_name='дата и время отключения')),
                ('city', models.CharField(default='Сегежа', max_length=200, verbose_name='город')),
                ('street', models.CharField(max_length=200, verbose_name='улица')),
                ('house', models.CharField(max_length=10, verbose_name='номер дома')),
                ('rest_address', models.CharField(blank=True, default='-', max_length=250, verbose_name='остаток адреса')),
                ('meter_brand', models.CharField(blank=True, default='-', max_length=100, verbose_name='марка счетчика')),
                ('number_meter', models.CharField(blank=True, default='-', max_length=30, verbose_name='номер счетчика')),
                ('number_seal', models.CharField(max_length=20, verbose_name='номер пломбы')),
                ('reading', models.CharField(max_length=100, verbose_name='показания счетчика')),
                ('reason', models.TextField(blank=True, default='-', max_length=200, verbose_name='причина отключения')),
                ('shutdown_method', models.TextField(blank=True, default='отключение отходящего фазного провода от счетчика', max_length=250, verbose_name='способ отключения')),
            ],
            options={
                'verbose_name': 'отключенный абонент',
                'verbose_name_plural': 'отключенные абоненты',
            },
        ),
    ]
