# Generated by Django 3.2.3 on 2022-05-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disabled_address_lists', '0003_alter_disabledadressesmodel_blackout_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disabledadressesmodel',
            name='blackout_datetime',
            field=models.CharField(default='10.05.2022-17.30', max_length=20, verbose_name='дата и время отключения'),
        ),
    ]
