# Generated by Django 3.2.3 on 2022-05-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='Сегежа', max_length=200, verbose_name='город')),
                ('street', models.CharField(max_length=200, verbose_name='улица')),
                ('house', models.CharField(max_length=10, verbose_name='номер дома')),
                ('note', models.CharField(blank=True, default='-', max_length=250, verbose_name='остаток адреса')),
            ],
            options={
                'verbose_name': 'обслуживаемый адрес',
                'verbose_name_plural': 'обслуживаемые адреса',
            },
        ),
    ]
